// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <bpfcore/vmlinux.h>
#include <bpfcore/bpf_core_read.h>
#include <bpfcore/bpf_helpers.h>

struct sock_port_ns {
    u32 netns;
    u16 port;
    u8 _pad[2];
};

// Emit this type to autogenerated bpf2go types.
const struct sock_port_ns *__pn_unused __attribute__((unused));

static __always_inline struct sock_port_ns sock_port_ns_from_skc(const struct sock_common *skc) {
    struct sock_port_ns pn = {
        .port = BPF_CORE_READ(skc, skc_num),
        .netns = BPF_CORE_READ(skc, skc_net.net, ns.inum),
    };
    return pn;
}

static __always_inline struct sock_port_ns sock_port_ns_from_sk(const struct sock *sk) {
    struct sock_common *skc = (struct sock_common *)sk;
    return sock_port_ns_from_skc(skc);
}

static __always_inline u64 netns_cookie_from_net(const struct net *net) {
    if (!net || !bpf_core_field_exists(net->net_cookie)) {
        return 0;
    }
    return BPF_CORE_READ(net, net_cookie);
}

static __always_inline u64 sock_netns_cookie_from_sk(const struct sock *sk) {
    const struct sock_common *skc = (const struct sock_common *)sk;
    const struct net *net = BPF_CORE_READ(skc, skc_net.net);
    return netns_cookie_from_net(net);
}

static __always_inline u32 task_netns() {
    struct task_struct *task = (struct task_struct *)bpf_get_current_task();
    return (u32)BPF_CORE_READ(task, nsproxy, net_ns, ns.inum);
}

static __always_inline u64 task_netns_cookie() {
    const struct task_struct *task = (const struct task_struct *)bpf_get_current_task();
    const struct net *net = BPF_CORE_READ(task, nsproxy, net_ns);
    return netns_cookie_from_net(net);
}
